name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker run -d -p 9000:9000 --name sonarqube-container sonarqube:latest
          sleep 30 # Wait for SonarQube to start

      - name: Install ngrok via Docker
        run: |
          docker pull ngrok/ngrok
          docker run -d --name ngrok-container ngrok/ngrok ngrok http 9000 --log=stdout
          sleep 10 # Wait for ngrok to start

      - name: Check running containers
        run: docker ps

      - name: Authenticate ngrok (using secrets)
        run: docker exec ngrok-container ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Get ngrok URL
        run: |
          docker exec ngrok-container curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url > ngrok_url.txt

      - name: Print ngrok URL
        run: cat ngrok_url.txt
