name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker network
        run: |
          docker network create sonarqube-network

      - name: Set up SonarQube
        run: |
          docker run -d --network sonarqube-network -p 9000:9000 --name sonarqube-container sonarqube:latest
          sleep 60 # Wait for SonarQube to start

      - name: Check SonarQube logs
        run: docker logs sonarqube-container

      - name: Set up ngrok
        run: |
          docker pull ngrok/ngrok
          docker run --network sonarqube-network -d --name ngrok-container -e NGROK_AUTHTOKEN=${{ secrets.NGROK_AUTH_TOKEN }} ngrok/ngrok:latest http 9000
          sleep 10 # Wait for ngrok to start

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest

      - name: Check running containers
        run: docker ps

      - name: Log ngrok container
        run: docker logs ngrok-container

      - name: Get ngrok URL
        run: |
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url > ngrok_url.txt

      - name: Print ngrok URL
        run: cat ngrok_url.txt

      - name: Stop existing Shopify tunnel
        run: shopify app tunnel stop

      - name: Start Shopify tunnel and capture URL
        run: |
          shopify app tunnel start &
          sleep 10 # Wait for tunnel to start
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url > shopify_tunnel_url.txt

      - name: Print Shopify tunnel URL
        run: cat shopify_tunnel_url.txt

      - name: Verify ngrok tunnel
        run: |
          NGROK_URL=$(cat ngrok_url.txt)
          echo "Verifying ngrok tunnel at $NGROK_URL"
          curl -s -I $NGROK_URL | head -n 1

      - name: Restart ngrok tunnel if needed
        if: failure()
        run: |
          docker stop ngrok-container
          docker rm ngrok-container
          docker run --network sonarqube-network -d --name ngrok-container -e NGROK_AUTHTOKEN=${{ secrets.NGROK_AUTH_TOKEN }} ngrok/ngrok:latest http 9000
          sleep 10 # Wait for ngrok to start
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url > ngrok_url.txt

      - name: Print new ngrok URL
        if: failure()
        run: cat ngrok_url.txt

      - name: Check SonarQube status via ngrok
        run: |
          NGROK_URL=$(cat ngrok_url.txt)
          echo "Checking SonarQube status at $NGROK_URL"
          curl -s -I "$NGROK_URL/api/system/status" | head -n 1

      - name: Test access to SonarQube via ngrok
        run: |
          NGROK_URL=$(cat ngrok_url.txt)
          echo "Testing access to SonarQube via $NGROK_URL"
          curl -s "$NGROK_URL/api/system/status" | jq .
