name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SonarQube
        run: |
          # Example: Download and install SonarQube on Windows
          Invoke-WebRequest -Uri 'https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.2.3.37887.zip' -OutFile 'sonarqube.zip'
          Expand-Archive -Path 'sonarqube.zip' -DestinationPath 'C:\sonarqube'
          Set-Location -Path 'C:\sonarqube\sonarqube-9.2.3.37887\bin\windows-x86-64'
          Start-Process 'StartSonar.bat' -NoNewWindow

      - name: Install ngrok
        run: choco install ngrok

      - name: Authenticate ngrok (using secrets)
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start ngrok (background process and log capture)
        run: |
          ngrok http 9000 --log=stdout > ngrok.log &

      - name: Wait for ngrok to start
        run: Start-Sleep -Seconds 10

      - name: Get ngrok URL
        run: |
          Invoke-RestMethod -Uri 'http://localhost:4040/api/tunnels' | Select-Object -ExpandProperty tunnels | Select-Object -First 1 -ExpandProperty public_url > ngrok_url.txt

      - name: Print ngrok URL
        run: type ngrok_url.txt
